const PDFDocument = require('pdfkit');
const fs = require('fs');

function generatePDF(itinerary, filePath) {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 50
  });
  
  doc.pipe(fs.createWriteStream(filePath));
  
  // Header
  doc.fontSize(24)
     .font('Helvetica-Bold')
     .text('Travel Itinerary', { align: 'center' });
  
  doc.moveDown();
  
  // Destination info
  if (itinerary.destination) {
    doc.fontSize(18)
       .font('Helvetica-Bold')
       .text(`${itinerary.destination} - ${itinerary.duration}`);
    
    doc.moveDown();
    
    // Interests
    if (itinerary.interests && itinerary.interests.length > 0) {
      doc.fontSize(14)
         .font('Helvetica-Bold')
         .text('Interests:');
      doc.fontSize(12)
         .font('Helvetica')
         .text(itinerary.interests.join(', '));
      doc.moveDown();
    }
  }
  
  // Daily itinerary
  if (itinerary.itinerary && Array.isArray(itinerary.itinerary)) {
    itinerary.itinerary.forEach((day, index) => {
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text(`Day ${day.day} - ${day.date}`);
      
      doc.moveDown(0.5);
      
      day.activities.forEach((activity, actIndex) => {
        doc.fontSize(12)
           .font('Helvetica-Bold')
           .text(`${activity.time} - ${activity.activity}`);
        
        doc.fontSize(10)
           .font('Helvetica')
           .text(`📍 ${activity.location}`, { indent: 20 });
        
        if (activity.type) {
          doc.fontSize(10)
             .font('Helvetica-Oblique')
             .text(`Type: ${activity.type}`, { indent: 20 });
        }
        
        if (actIndex < day.activities.length - 1) {
          doc.moveDown(0.5);
        }
      });
      
      if (index < itinerary.itinerary.length - 1) {
        doc.moveDown();
        doc.moveTo(50, doc.y)
           .lineTo(550, doc.y)
           .stroke();
        doc.moveDown();
      }
    });
  } else {
    // Fallback for raw text
    doc.fontSize(12)
       .font('Helvetica')
       .text(itinerary.itinerary || itinerary);
  }
  
  // Footer
  doc.fontSize(10)
     .font('Helvetica-Oblique')
     .text('Generated by AI Travel Planner', { align: 'center' });
  
  doc.end();
}

module.exports = { generatePDF };
