const TelegramBot = require('node-telegram-bot-api');

// Initialize bot (token will be set from environment variable)
let bot = null;

function initializeBot(token) {
  if (token && token !== 'your_telegram_bot_token_here') {
    bot = new TelegramBot(token, { polling: false });
    return true;
  }
  return false;
}

async function sendTelegramMessage(chatId, message) {
  try {
    if (!bot) {
      throw new Error('Telegram bot not initialized. Please add your bot token to config.env');
    }
    
    const result = await bot.sendMessage(chatId, message, {
      parse_mode: 'HTML',
      disable_web_page_preview: true
    });
    
    return { success: true, messageId: result.message_id };
  } catch (error) {
    console.error('Error sending Telegram message:', error);
    throw new Error('Failed to send Telegram message: ' + error.message);
  }
}

function formatItineraryForTelegram(itinerary) {
  let message = `✈️ <b>Travel Itinerary</b>\n\n`;
  
  if (itinerary.destination) {
    message += `📍 <b>Destination:</b> ${itinerary.destination}\n`;
    message += `⏱️ <b>Duration:</b> ${itinerary.duration}\n\n`;
  }
  
  if (itinerary.interests && itinerary.interests.length > 0) {
    message += `🎯 <b>Interests:</b> ${itinerary.interests.join(', ')}\n\n`;
  }
  
  if (itinerary.itinerary && Array.isArray(itinerary.itinerary)) {
    itinerary.itinerary.forEach((day, index) => {
      message += `📅 <b>Day ${day.day} - ${day.date}</b>\n`;
      
      day.activities.forEach((activity, actIndex) => {
        const icon = getActivityIcon(activity.type);
        message += `${icon} <b>${activity.time}</b> - ${activity.activity}\n`;
        if (activity.location) {
          message += `📍 ${activity.location}\n`;
        }
        message += `\n`;
      });
      
      if (index < itinerary.itinerary.length - 1) {
        message += `─────────────────\n\n`;
      }
    });
  } else {
    // Fallback for raw text
    message += itinerary.itinerary || itinerary;
  }
  
  message += `\n\n<i>Generated by AI Travel Planner ✨</i>`;
  
  return message;
}

function getActivityIcon(type) {
  switch (type) {
    case 'sightseeing': return '🏛️';
    case 'food': return '🍽️';
    case 'adventure': return '🏔️';
    case 'culture': return '🎭';
    case 'shopping': return '🛍️';
    case 'relaxation': return '🧘';
    default: return '📍';
  }
}

module.exports = { 
  initializeBot, 
  sendTelegramMessage, 
  formatItineraryForTelegram 
}; 